baseURL = "http://thadanderson.me"
languageCode = "en-us"
title = "Thaddeus Anderson"
theme = "nix"
googleAnalytics = "G-VW04T10SPR"

[context.production.environment]
HUGO_VERSION = "0.47.1"

[params]
  Name = "Thaddeus Anderson"
  Extra = "thadandlaura.com"
  #GithubID = "thaddeusa"
  #TwitterID = "thaddeusa"
  #LinkedInID = "thaddeusa"
  About = "I’m an IT professional with a passion for [automating] the cloud. I love proactively finding solutions to problems and automating my way out of repetitive tasks. I like to stay ahead of things, but you’ll never find me running from a good firefight. My experience ranges from Security Engineer, Platform/Automation Engineer to Solutions Architect to IT Manager to Consultant. I’m currently a Principal Security Engineer for Empower, architecting security solutions and automating them, primarily on the AWS cloud. My automation toolkit includes terraform, CloudFormation/CDK, gitlab CI, and python, to name a few. I currently hold all 5 AWS role-based certs, the AWS Certified Security - Specialty, and CISSP."
