baseURL = "http://thadanderson.me"
languageCode = "en-us"
title = "Thaddeus Anderson"
theme = "nix"
googleAnalytics = "UA-125351911-1"

[context.production.environment]
HUGO_VERSION = "0.47.1"

[params]
  Name = "Thaddeus Anderson"
  Extra = "thadandlaura.com"
  #GithubID = "thaddeusa"
  #TwitterID = "thaddeusa"
  #LinkedInID = "thaddeusa"
  About = "I’m an IT professional with a passion for [automating] the cloud. I love proactively finding solutions to problems and automating my way out of repetitive tasks. I like to stay ahead of things, but you’ll never find me running from a good firefight. My experience ranges from Platform/Automation Engineer to Solutions Architect to IT Manager to Consultant. I’m currently a Senior Cloud Engineer for ANM, architecting solutions and automating them, primarily on the AWS cloud. My automation toolkit includes terraform, CloudFormation, CodePipeline, and python. I currently hold all 5 AWS role-based certs"