[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
# Redirect default Netlify subdomain to primary domain
from = "https://thadandersonme.netlify.com/*"
to = "http://www.thadanderson.me/:splat"
status = 301

[[redirects]]
# Redirect default Netlify subdomain to primary domain
from = "http://thadandersonme.netlify.com"
to = "http://www.thadanderson.me"
status = 301


#
# [context.split1]
# command = "hugo --enableGitInfo"
#
# [context.split1.environment]
# HUGO_VERSION = "0.47.1"
# HUGO_ENV = "production"
#
# [context.deploy-preview]
# command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
#
# [context.deploy-preview.environment]
# HUGO_VERSION = "0.47.1"
#
# [context.branch-deploy]
# command = "hugo -b $DEPLOY_PRIME_URL"
#
# [context.branch-deploy.environment]
# HUGO_VERSION = "0.47.1"
#
# [context.next.environment]
# HUGO_ENABLEGITINFO = "true"
